# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RCRSLogProto.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RCRSProto_pb2 as RCRSProto__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12RCRSLogProto.proto\x1a\x0fRCRSProto.proto\"\x9e\x02\n\x08LogProto\x12\x1f\n\x05start\x18\x01 \x01(\x0b\x32\x0e.StartLogProtoH\x00\x12\x36\n\x10initialCondition\x18\x02 \x01(\x0b\x32\x1a.InitialConditionsLogProtoH\x00\x12#\n\x07\x63ommand\x18\x03 \x01(\x0b\x32\x10.CommandLogProtoH\x00\x12)\n\nperception\x18\x04 \x01(\x0b\x32\x13.PerceptionLogProtoH\x00\x12!\n\x06\x63onfig\x18\x05 \x01(\x0b\x32\x0f.ConfigLogProtoH\x00\x12\"\n\x06update\x18\x06 \x01(\x0b\x32\x10.UpdatesLogProtoH\x00\x12\x1b\n\x03\x65nd\x18\x07 \x01(\x0b\x32\x0c.EndLogProtoH\x00\x42\x05\n\x03log\"\x0f\n\rStartLogProto\";\n\x19InitialConditionsLogProto\x12\x1e\n\x08\x65ntities\x18\x01 \x03(\x0b\x32\x0c.EntityProto\"@\n\x0f\x43ommandLogProto\x12\x0c\n\x04time\x18\x01 \x01(\x05\x12\x1f\n\x08\x63ommands\x18\x02 \x03(\x0b\x32\r.MessageProto\"}\n\x12PerceptionLogProto\x12\x0c\n\x04time\x18\x01 \x01(\x05\x12\x10\n\x08\x65ntityID\x18\x02 \x01(\x05\x12 \n\x07visible\x18\x03 \x01(\x0b\x32\x0f.ChangeSetProto\x12%\n\x0e\x63ommunications\x18\x04 \x03(\x0b\x32\r.MessageProto\".\n\x0e\x43onfigLogProto\x12\x1c\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x0c.ConfigProto\"A\n\x0fUpdatesLogProto\x12\x0c\n\x04time\x18\x01 \x01(\x05\x12 \n\x07\x63hanges\x18\x02 \x01(\x0b\x32\x0f.ChangeSetProto\"\r\n\x0b\x45ndLogProtoB-\n\x1drescuecore2.messages.protobufB\x0cRCRSLogProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RCRSLogProto_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035rescuecore2.messages.protobufB\014RCRSLogProto'
  _globals['_LOGPROTO']._serialized_start=40
  _globals['_LOGPROTO']._serialized_end=326
  _globals['_STARTLOGPROTO']._serialized_start=328
  _globals['_STARTLOGPROTO']._serialized_end=343
  _globals['_INITIALCONDITIONSLOGPROTO']._serialized_start=345
  _globals['_INITIALCONDITIONSLOGPROTO']._serialized_end=404
  _globals['_COMMANDLOGPROTO']._serialized_start=406
  _globals['_COMMANDLOGPROTO']._serialized_end=470
  _globals['_PERCEPTIONLOGPROTO']._serialized_start=472
  _globals['_PERCEPTIONLOGPROTO']._serialized_end=597
  _globals['_CONFIGLOGPROTO']._serialized_start=599
  _globals['_CONFIGLOGPROTO']._serialized_end=645
  _globals['_UPDATESLOGPROTO']._serialized_start=647
  _globals['_UPDATESLOGPROTO']._serialized_end=712
  _globals['_ENDLOGPROTO']._serialized_start=714
  _globals['_ENDLOGPROTO']._serialized_end=727
# @@protoc_insertion_point(module_scope)
